title: Xin Wang 王鑫
url: "https://wangxinalice.com"
#baseurl: "/researcher"

nav:
#  - name: "About"
#    link: "/researcher/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "XIR Project (Xin's Investment Research)"
   link: "inv-res/index"

#theme: jekyll-theme-cayman
#remote_theme: ankitsultana/researcher@gem
#theme: ankitsultana/researcher@gem

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass