title: UCMW - You See My World
url: "https://yisong.me"
#baseurl: "/researcher"

nav:
#  - name: "About"
#    link: "/researcher/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "Home"
   link: "/"

#theme: jekyll-theme-cayman
#remote_theme: ankitsultana/researcher@gem
#theme: ankitsultana/researcher@gem

markdown: kramdown

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass